# Crate Configuration
network.host: _tailscale0_,_local_
cluster.graceful_stop.min_availability: primaries
cluster.routing.allocation.awareness.attributes: location
gateway.auto_import_dangling_indices: true
node.store.allow_mmap: false
http.cors.enabled: true
http.cors.allow-origin: "/*"
stats.enabled: false



# Paths
path:
  logs: /data/crate/log
  data: /data/crate/data
blobs:
  path: /data/crate/blobs
