# Crate Configuration

network.host=_tailscale0_,_local_
cluster.graceful_stop.min_availability=primaries
stats.enabled=false
# Paths
path:
  logs: /data/log
  data: /data/data
blobs:
  path: /data/blobs
