# Crate Configuration
discovery.seed_hosts: nexus.chimp-beta.ts.net
network.host: _tailscale0_,_local_
network.publish_host: _tailscale0_
cluster.name: cluster-anywhere
cluster.graceful_stop.min_availability: primaries
cluster.routing.allocation.awareness.attributes: location
cluster.routing.allocation.awareness.force.zone.values: OnPrem,AWS,GCP,Azure
gateway.auto_import_dangling_indices: true
node.name: ${HOSTNAME}
node.attr.location: ${LOCATION}
node.store.allow_mmap: false
node.data: true
http.cors.enabled: true
http.cors.allow-origin: "/*"
stats.enabled: false



# Paths
path:
  logs: /data/crate/log
  data: /data/crate/data
blobs:
  path: /data/crate/blobs
