# Crate Configuration

network.host:_tailscale0_,_local_
cluster.initial_master_nodes:nexus
cluster.graceful_stop.min_availability:primaries
cluster.routing.allocation.awareness.attributes:location
stats.enabled:false
gateway.recover_after_nodes:3
http.cors.enabled:true
http.cors.allow-origin:"/*"



# Paths
path:
  logs: /data/log
  data: /data/data
blobs:
  path: /data/blobs
